namespace: dev-dds
environment: nonprod
metaLabels:
  - name: environment
    value: production
redis:
  resources:
    limits:
      cpu: 100m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 1024Mi
