namespace: dev-dds
clusterDomain: cluster.local
environment: nonprod
enableAvi: true
nameOverride: ""
backwardsCompatable: false
fullnameOverride: ""
metaLabels:
  - name: domain
    value: dds
  - name: app
    value: redis
  - name: task
    value: redis-msp
  - name: team
    value: dds
users:
  producer: on ~* +@read +@write nopass
  consumer: on ~* +@read nopass
redis: 
  stateful: true
  slaveCount: 3
  sentinelCount: 3
  image:
    registry: docker.io
    repository: redis
    pullPolicy: IfNotPresent
    tag: 6.0.4
  service:
    type: ClusterIP
    port: 6379
    annotations:
      app.kubernetes.io/name: redis-msp
      app.kubernetes.io/instance: redis-msp
      app.kubernetes.io/version: 6.0.3
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  resources:
    limits:
      cpu: 50m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 512Mi
  storage: 2048Mi
  config:
    port: 6379
    sentinelPort: 26379
    maxmemory: 1024mb
    maxmemoryPolicy: allkeys-lru
    dir: /data
    appendonly: "yes"
    appendfsync: everysec
    replDisklessSync: "yes"
    hz: 50
    noAppendfsyncOnRewrite: "no"
    autoAofRewriteMinSize: 256mb
    autoAofRewritePercentage: 100
    replDisklessSync: "yes"
    replTimeout: 360
    replBacklogSize: 100mb
prometheus:
  enabled: true
  image:
    registry: docker.io
    repository: oliver006/redis_exporter
    pullPolicy: IfNotPresent
    tag: v0.21.1
  service:
    type: ClusterIP
    port: 9121
  resources:
    limits:
      cpu: 100m
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 128Mi
serviceAccount:
  create: true
  name: ""
  annotations: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: 
  allowPrivilegeEscalation: false
nodeSelector: {}
tolerations: []
affinity: {}
