{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-exporter
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "redis-dds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        {{- include "generic.vaultAnnotations" . | nindent 8 }}
        prometheus.io/ddsscrape: "true"
        prometheus.io/environment: "{{ .Values.environment }}"
        prometheus.io/technology: "redis"
        prometheus.io/exporter: "redis-exporter"
        prometheus.io/port: "9121"
      labels:
        {{- include "redis-dds.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "redis-dds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.authentication.enabled }}
          command: ["/scripts/entrypoint.sh"]
          {{- end }}
          env: 
            - name: REDIS_ALIAS
              value: {{ .Release.Name }}
            - name: REDIS_ADDR
              value: redis://{{ .Release.Name }}.{{ .Values.ingress.domain }}:6379
              {{- end }}
            - name: REDIS_EXPORTER_LOG_FORMAT
              value: json
            - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
              value: "true"
            - name: REDIS_EXPORTER_PING_ON_CONNECT
              value: "true"
          {{- if .Values.authentication.enabled }}
          volumeMounts:
          - name: entrypoint
            mountPath: /scripts
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.exporter.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
      {{- if .Values.authentication.enabled }}
      volumes:
        - name: entrypoint
          configMap:
            name: {{ .Release.Name }}-exporter-entrypoint
            defaultMode: 0755
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
