{{ if .Values.enableAvi }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "redis-dds.fullname" . }}-ingress"
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
  annotations:
    avi_proxy: '{
        "virtualservice":{
          "fqdn": "{{ .Release.Name }}.{{ .Values.ingress.domain }}",
          "services":[{"port": 6379}],
          "application_profile_ref": "/api/applicationprofile?name=System-L4-Application",
          "network_profile_ref": "/api/networkprofile?name=System-TCP-Proxy",
          "http_policies": []
        },
        "gslbservice":{
            "name": "{{ .Release.Name }}",
            "domain_names": ["{{ .Release.Name }}.{{ .Values.ingress.gslbDomain }}"],
            "groups": [{"members": [{"ratio": 20}]}],
            "health_monitor_refs": [
              "gslb-redis"
            ]
        }
    }'
spec:
  backend:
    serviceName: {{ .Release.Name }}-replicas
    {{ if eq (.Values.redis.replicas | int) 1 }}
    servicePort: {{ .Values.redis.config.port }}
    {{- else }}
    servicePort: {{ .Values.proxy.service.port }}
    {{- end }}
{{- end }}
