{{ if or (gt (.Values.redis.replicas | int) 1) (.Values.stateful) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-replicas-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None 
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.redis.config.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/role: "replica"
    {{- include "redis-dds.selectorLabels" . | nindent 4 }}
{{- end }}
