{{ if gt (.Values.redis.slaveCount | int) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-dds.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  type: ClusterIP
  clusterIP: None 
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    - port: {{ .Values.sentinel.config.port }}
      targetPort: sentinel
      protocol: TCP
      name: sentinel
  selector:
    {{- include "redis-dds.selectorLabels" . | nindent 4 }}
{{- end }}
