apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-replicas
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
{{ if gt (.Values.redis.replicas | int) 1 }}
    - port: {{ .Values.proxy.service.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
{{- end }}
  selector:
    app.kubernetes.io/role: "replica"
    {{- include "redis-dds.selectorLabels" . | nindent 4 }}
