{{ if gt (.Values.redis.replicas | int) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sentinels
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sentinel.service.type }}
  type: NodePort
  ports:
    - port: {{ .Values.sentinel.service.port }}
      targetPort: sentinel
      protocol: TCP
      name: sentinel
  selector:
    {{- include "redis-dds.selectorLabels" . | nindent 4 }}
{{- end }}
