apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
  annotations:
    prometheus.io/ddsscrape: "true"
    prometheus.io/port: "9121"
spec:
  {{- if not .Values.enableAvi }}
  type: {{ .Values.redis.service.type }}
  {{ else }}
  type: NodePort
  {{ end }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    - port: {{ .Values.prometheus.service.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
{{ if gt (.Values.redis.replicas | int) 1 }}
    - port: {{ .Values.proxy.service.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: {{ .Values.sentinel.service.port }}
      targetPort: sentinel
      protocol: TCP
      name: sentinel
{{- end }}
  selector:
    {{- include "redis-dds.selectorLabels" . | nindent 4 }}
