{{ if .Values.redis.ako.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loadbalancer
  namespace: {{ .Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}.{{ .Values.ingress.domain }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.redis.ako.port }}
    {{- if eq (.Values.redis.replicas | int) 1 }}
    targetPort: {{ .Values.redis.config.port }}
    {{- else }}
    targetPort: {{ .Values.proxy.service.port }}
    {{- end }}
    name: redis
  selector:
    app.kubernetes.io/role: "replica"
    {{- include "redis-dds.selectorLabels" . | nindent 4 }}
{{- end }}
