apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-dds.fullname" . }}
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
  annotations:
    prometheus.io/ddsscrape: "true"
    prometheus.io/port: "9121"
spec:
  {{- if not .Values.enableAvi }}
  type: {{ .Values.redis.service.type }}
  {{ else }}
  type: NodePort
  {{ end }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    - port: {{ .Values.prometheus.service.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "redis-dds.selectorLabels" . | nindent 4 }}
