apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    {{- include "redis-dds.labels" . | nindent 4 }}
  annotations:
    prometheus.io/ddsscrape: "true"
    prometheus.io/port: "9121"
spec:
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "redis-dds.selectorLabels" . | nindent 4 }}
