clusterDomain: cluster.local
environment: dev
nameOverride: ""
fullnameOverride: ""

image:
  registry: docker.io
  repository: redis
  pullPolicy: IfNotPresent
  tag: 6.0.4
  command: redis-server
redis: 
  size: 1024
  buffer: 1024
  stateful: 
    enabled: false
  replicas: 1
  ako:
    enabled: false
    port: 6379
  service:
    type: LoadBalancer
    annotations:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis
      app.kubernetes.io/version: 6.0.4
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 10m
  config:
    port: 6379
    maxmemoryPolicy: allkeys-lru
    dir: /data
    appendonly: "yes"
    appendfsync: everysec
    replDisklessSync: "yes"
    hz: 50
    noAppendfsyncOnRewrite: "no"
    autoAofRewriteMinSize: 256mb
    autoAofRewritePercentage: 100
    replDisklessSync: "yes"
    replTimeout: 360
    replBacklogSize: 100mb
    timeout: 360
    databases: 32
  startup:
    healthCheckCount: 30
    sleepTime: 5
