clusterDomain: cluster.local
environment: dev
nameOverride: ""
fullnameOverride: ""

vault:
  # K8s role that is declared in vault
  enabled: false
authentication:
  enabled: false
image:
  registry: docker.io
  repository: redis
  pullPolicy: IfNotPresent
  tag: 6.0.4
  command: redis-server
redis: 
  size: 1024
  buffer: 1024
  stateful: 
    enabled: false
  replicas: 1
  ako:
    enabled: false
    port: 6379
  service:
    type: ClusterIP
    annotations:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis
      app.kubernetes.io/version: 6.0.4
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 10m
  config:
    port: 6379
    targetPort: 6379
    maxmemoryPolicy: allkeys-lru
    dir: /data
    appendonly: "yes"
    appendfsync: everysec
    replDisklessSync: "yes"
    hz: 50
    noAppendfsyncOnRewrite: "no"
    autoAofRewriteMinSize: 256mb
    autoAofRewritePercentage: 100
    replDisklessSync: "yes"
    replTimeout: 360
    replBacklogSize: 100mb
    timeout: 360
    databases: 32
  startup:
    healthCheckCount: 30
    sleepTime: 5
sentinel: 
  replicas: 2
  service:
    type: ClusterIP
    annotations:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: redis
      app.kubernetes.io/version: 6.0.4
      service.beta.kubernetes.io/azure-load-balancer-internal: "false"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi
  config:
    port: 26379
    dir: /data
    downAfterMilliseconds: 10000
    parallelSyncs: 2
    failoverTimeout: 18000    
proxy:
  image:
    registry: docker.io
    repository: findelabs/redis-rust-proxy
    pullPolicy: IfNotPresent
    tag: 0.2.11
  service: 
    type: ClusterIP
    port: 6378
  resources:
    limits:
      cpu: 1000m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi    
serviceAccount:
  create: true
  name: ""
  annotations: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: 
  allowPrivilegeEscalation: false
nodeSelector: {}
tolerations: []
affinity: {}
